### ISSUE TITLE
Caveats?

### ISSUE THREAD

**Issue by f1vefour** [jackcolentern/openwrt-linksys-ea7500v2-bin#1]
What were some if any caveats to the build as you left it? Any problems?

5ghz fully functional?

**Comment by jackcolentern** [comment]
Hi, this bin is not signed so you can't flash it in Linksys web interface.
5ghz WiFi is working well (using closed sourced driver)
This build is using outdated kernel version so you can't install some packages

**Comment by f1vefour** [comment]
How did you flash, over serial?

**Comment by jackcolentern** [comment]
@f1vefour ya you need serial and tftp to flash for now
